services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pass123
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: >
      bash -c "
        echo 'CREATE EXTENSION postgis;' >> /docker-entrypoint-initdb.d/init.sql
        echo 'CREATE EXTENSION postgis_topology;' >> /docker-entrypoint-initdb.d/init.sql
        docker-entrypoint.sh postgres
      "