services:
  db:
    image: postgis/postgis:15-3.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${PGIS_USERNAME}
      - POSTGRES_PASSWORD=${PGIS_PASSWORD}
      - POSTGRES_DB=${PGIS_NAME}
    env_file:
      - ./api/.env
    volumes:
      - ./data:/var/lib/postgresql/data